allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  bigint-buffer: false
  bufferutil: true
  sharp: true
  tiny-secp256k1: true
  utf-8-validate: true
ignoredBuiltDependencies:
  - bigint-buffer
  - sharp
  - unrs-resolver
auditConfig:
  ignoreGhsas:
    - GHSA-qx2v-qp2m-jg93
