allowBuilds:
  '@parcel/watcher': set this to true or false
  '@swc/core': set this to true or false
  bufferutil: set this to true or false
  sharp: set this to true or false
  utf-8-validate: set this to true or false
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
